#This part groups pokemon in their evolution groups

all_evolutions = {
  "Bulbasaur": ["Bulbasaur", "Ivysaur", "Venusaur"],
  "Charmander": ["Charmander", "Charmeleon", "Charizard"],
  "Squirtle": ["Squirtle", "Wartortle", "Blastoise"],
  "Caterpie": ["Caterpie", "Metapod", "Butterfree"],
  "Weedle": ["Weedle", "Kakuna", "Beedrill"],
  "Pidgey": ["Pidgey", "Pidgeotto", "Pidgeot"],
  "Rattata": ["Rattata", "Raticate"],
  "Spearow": ["Spearow", "Fearow"],
  "Ekans": ["Ekans", "Arbok"],
  "Pikachu": ["Pikachu", "Raichu"], 
  "Sandshrew": ["Sandshrew", "Sandslash"],
  "Nidoran Female": ["Nidoran Female", "Nidorina", "Nidoqueen"],
  "Nidoran Male": ["Nidoran Male", "Nidorino", "Nidoking"],
  "Clefairy": ["Clefairy", "Clefable"],
  "Vulpix": ["Vulpix", "Ninetales"],
  "Jigglypuff": ["Jigglypuff", "Wigglytuff"],
  "Zubat": ["Zubat", "Golbat"],
  "Oddish": ["Oddish", "Gloom", "Vileplume"],
  "Paras": ["Paras", "Parasect"],
  "Venonat": ["Venonat", "Venomoth"],
  "Diglett": ["Diglett", "Dugtrio"],
  "Meowth": ["Meowth", "Persian"],
  "Psyduck": ["Psyduck", "Golduck"],
  "Mankey": ["Mankey", "Primeape"],
  "Growlithe": ["Growlithe", "Arcanine"],
  "Poliwag": ["Poliwag", "Poliwhirl", "Poliwrath"],
  "Abra": ["Abra", "Kadabra", "Alakazam"],
  "Machop": ["Machop", "Machoke", "Machamp"],
  "Bellsprout": ["Bellsprout", "Weepinbell", "Victreebel"],
  "Tentacool": ["Tentacool", "Tentacruel"],
  "Geodude": ["Geodude", "Graveler", "Golem"],
  "Ponyta": ["Ponyta", "Rapidash"],
  "Slowpoke": ["Slowpoke", "Slowbro"],
  "Magnemite": ["Magnemite", "Magneton"],
  "Farfetch'd": ["Farfetch'd"],
  "Doduo": ["Doduo", "Dodrio"],
  "Seel": ["Seel", "Dewgong"],
  "Grimer": ["Grimer", "Muk"],
  "Shellder": ["Shellder", "Cloyster"],
  "Gastly": ["Gastly", "Haunter", "Gengar"],
  "Onix": ["Onix"],
  "Drowzee": ["Drowzee", "Hypno"],
  "Krabby": ["Krabby", "Kingler"],
  "Voltorb": ["Voltorb", "Electrode"],
  "Exeggcute": ["Exeggcute", "Exeggutor"],
  "Cubone": ["Cubone", "Marowak"],
  "Hitmonlee": ["Hitmonlee"],
  "Hitmonchan": ["Hitmonchan"],
  "Lickitung": ["Lickitung"],
  "Koffing": ["Koffing", "Weezing"],
  "Rhyhorn": ["Rhyhorn", "Rhydon"],
  "Chansey": ["Chansey"],
  "Tangela": ["Tangela"],
  "Kangaskhan": ["Kangaskhan"],
  "Horsea": ["Horsea", "Seadra"],
  "Goldeen": ["Goldeen", "Seaking"],
  "Staryu": ["Staryu", "Starmie"],
  "Mr. Mime": ["Mr. Mime"],
  "Scyther": ["Scyther"],
  "Jynx": ["Jynx"],
  "Electabuzz": ["Electabuzz"],
  "Magmar": ["Magmar"],
  "Pinsir": ["Pinsir"],
  "Tauros": ["Tauros"],
  "Magikarp": ["Magikarp", "Gyarados"],
  "Lapras": ["Lapras"],
  "Ditto": ["Ditto"],
  "Eevee": ["Eevee"],
  "Vaporeon": ["Vaporeon"],
  "Jolteon": ["Jolteon"],
  "Flareon": ["Flareon"],
  "Porygon": ["Porygon"],
  "Omanyte": ["Omanyte", "Omastar"],
  "Kabuto": ["Kabuto", "Kabutops"],
  "Aerodactyl": ["Aerodactyl"],
  "Snorlax": ["Snorlax"],
  "Articuno": ["Articuno"],
  "Zapdos": ["Zapdos"],
  "Moltres": ["Moltres"],
  "Dratini": ["Dratini", "Dragonair", "Dragonite"],
  "Mewtwo": ["Mewtwo"],
  "Mew": ["Mew"]
}